name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies for ubuntu
      run: |
        chmod +x ./.github/actions/ubuntu-deps.sh
        .github/actions/ubuntu-deps.sh
    - name: submodule
      run: git submodule update --init --recursive
    - name: build
      run: |
        export PATH=~/.local/bin:$PATH
        export PKG_CONFIG_PATH=/usr/local/lib:${PKG_CONFIG_PATH}
        meson build && ninja -C build
